# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Users\jsoft\Programmieren\workspace-2020-09\Notes Import - Python\src\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(610, 600)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.labelExe = QtWidgets.QLabel(Dialog)
        self.labelExe.setObjectName("labelExe")
        self.gridLayout.addWidget(self.labelExe, 0, 0, 1, 1)
        self.lineEditExe = QtWidgets.QLineEdit(Dialog)
        self.lineEditExe.setObjectName("lineEditExe")
        self.gridLayout.addWidget(self.lineEditExe, 0, 1, 1, 1)
        self.pushButtonExe = QtWidgets.QPushButton(Dialog)
        self.pushButtonExe.setStyleSheet("QPushButton { font-weight: 500;  }")
        self.pushButtonExe.setObjectName("pushButtonExe")
        self.gridLayout.addWidget(self.pushButtonExe, 0, 2, 1, 1)
        self.labelToken = QtWidgets.QLabel(Dialog)
        self.labelToken.setObjectName("labelToken")
        self.gridLayout.addWidget(self.labelToken, 1, 0, 1, 1)
        self.lineEditToken = QtWidgets.QLineEdit(Dialog)
        self.lineEditToken.setObjectName("lineEditToken")
        self.gridLayout.addWidget(self.lineEditToken, 1, 1, 1, 1)
        self.pushButtonInvokeExe = QtWidgets.QPushButton(Dialog)
        self.pushButtonInvokeExe.setObjectName("pushButtonInvokeExe")
        self.gridLayout.addWidget(self.pushButtonInvokeExe, 1, 2, 1, 1)
        self.labelInsertion = QtWidgets.QLabel(Dialog)
        self.labelInsertion.setObjectName("labelInsertion")
        self.gridLayout.addWidget(self.labelInsertion, 2, 0, 1, 1)
        self.lineEditInsertion = QtWidgets.QLineEdit(Dialog)
        self.lineEditInsertion.setObjectName("lineEditInsertion")
        self.gridLayout.addWidget(self.lineEditInsertion, 2, 1, 1, 1)
        self.labelArchive = QtWidgets.QLabel(Dialog)
        self.labelArchive.setObjectName("labelArchive")
        self.gridLayout.addWidget(self.labelArchive, 3, 0, 1, 1)
        self.lineEditArchive = QtWidgets.QLineEdit(Dialog)
        self.lineEditArchive.setObjectName("lineEditArchive")
        self.gridLayout.addWidget(self.lineEditArchive, 3, 1, 1, 1)
        self.pushButtonArchive = QtWidgets.QPushButton(Dialog)
        self.pushButtonArchive.setStyleSheet("QPushButton { font-weight: 500;  }")
        self.pushButtonArchive.setObjectName("pushButtonArchive")
        self.gridLayout.addWidget(self.pushButtonArchive, 3, 2, 1, 1)
        self.pushButtonGo = QtWidgets.QPushButton(Dialog)
        self.pushButtonGo.setObjectName("pushButtonGo")
        self.gridLayout.addWidget(self.pushButtonGo, 4, 1, 1, 1)
        self.textEditOutput = QtWidgets.QTextEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.textEditOutput.setFont(font)
        self.textEditOutput.setReadOnly(True)
        self.textEditOutput.setObjectName("textEditOutput")
        self.gridLayout.addWidget(self.textEditOutput, 5, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelExe.setText(_translate("Dialog", "Joplin Exe:"))
        self.pushButtonExe.setText(_translate("Dialog", "..."))
        self.labelToken.setText(_translate("Dialog", "Joplin Token:"))
        self.pushButtonInvokeExe.setText(_translate("Dialog", "Invoke Joplin"))
        self.labelInsertion.setText(_translate("Dialog", "Insertion Point:"))
        self.labelArchive.setText(_translate("Dialog", "Archive:"))
        self.pushButtonArchive.setText(_translate("Dialog", "..."))
        self.pushButtonGo.setText(_translate("Dialog", "Go"))
